import type { Metadata } from 'next';
import Image from 'next/image';
import BookingForm from './booking-form';
import { todayInSouthAfrica } from '@/lib/bookings';
import './book.css';

export const dynamic = 'force-dynamic';
export const metadata: Metadata = { title: 'Book your free demo | Elevate', description: 'See how your solar or pool business could win 2–3 extra jobs. Book a free 15-minute demo with Elevate.' };
const steps = [
  ['Bring in new opportunities', 'New leads can come from outreach, website forms, calls, WhatsApp or other lead sources.'],
  ['Track every opportunity', 'Every lead moves through one simple pipeline from first enquiry to quote and won job.'],
  ['Follow up consistently', 'See exactly who needs a follow-up so potential jobs do not get forgotten.'],
  ['Close more jobs', 'Your team gets a clear view of every live opportunity and what needs to happen next.'],
];
const Arrow = () => <span aria-hidden="true">↗</span>;
export default function BookPage() {
  return <div className="book-page"><div className="book-container">
    <header className="book-nav"><a className="book-brand" href="/book" aria-label="Elevate booking page"><span className="book-mark" aria-hidden="true">↗</span>Elevate<span className="book-brand-dot">.</span></a><a className="book-nav-link" href="#booking">Let’s talk <Arrow /></a></header>
    <main>
      <section className="book-hero" aria-labelledby="hero-title"><p className="book-kicker"><span className="book-dot" /> MORE OPPORTUNITIES. FEWER MISSED JOBS.</p><h1 id="hero-title">See how your business could win <span>2–3 extra jobs</span></h1><p className="book-hero-copy">We’ll show you how to bring more opportunities into your pipeline, follow up faster, and stop losing jobs through missed enquiries and forgotten quotes.</p><a className="book-button book-hero-cta" href="#booking">Book My Free Demo <Arrow /></a><p className="book-small">15 minutes. No commitment.</p><div className="book-industry"><span aria-hidden="true">☀</span> Built for solar and pool companies.</div><span className="book-hero-index" aria-hidden="true">01 — A CLEARER PATH TO YOUR NEXT JOB</span></section>
      <section className="book-revenue book-section" aria-labelledby="revenue-title"><div className="book-section-top"><div><p className="book-kicker">THE OPPORTUNITY</p><h2 id="revenue-title">What 2–3 extra jobs could mean<br className="book-desktop-break" /> for your business</h2></div><span className="book-example">Example revenue only</span></div><div className="book-revenue-grid">{[1, 2, 3].map((jobs) => <article key={jobs} className={`book-revenue-card ${jobs === 3 ? 'book-revenue-featured' : ''}`}><div className="book-card-top"><span>{jobs} extra {jobs === 1 ? 'job' : 'jobs'}</span><span aria-hidden="true">{'▮'.repeat(jobs)}</span></div><strong>R{(jobs * 15000).toLocaleString('en-ZA').replace(/\s/g, ',')}</strong><span className="book-small">in potential additional revenue</span></article>)}</div><p className="book-small book-revenue-note">Illustration based on R15,000 per job. Actual job values and results vary. These are examples, not guaranteed results.</p></section>
      <section className="book-section" aria-labelledby="dashboard-title"><p className="book-kicker">NOTHING SLIPS THROUGH THE CRACKS</p><h2 id="dashboard-title">See exactly where<br />your revenue is sitting</h2><p className="book-section-copy">One clear view of your enquiries, open quotes and next follow-ups.</p><div className="book-gallery">{[['overview', 'Know exactly what revenue is still open'], ['pipeline', 'Track every enquiry']].map(([image, caption]) => <figure key={image}><div className="book-preview"><div className="book-preview-bar"><span className="book-window-dots" aria-hidden="true">● ● ●</span><span>Demo dashboard</span><span aria-hidden="true">↗</span></div><Image src={`/book/${image}.svg`} alt={`Demo dashboard placeholder: ${image === 'overview' ? 'Open Quote Value, Won Revenue, New Enquiries, Quotes Pending and Follow-Ups Due' : 'leads moving from new enquiry to quoted, follow-up and won stages'}. Illustrative layout only.`} width={720} height={480} /></div><figcaption><span className="book-caption-line" />{caption}</figcaption></figure>)}</div><p className="book-small">See which quotes need follow-up. Demo dashboard placeholders show the layout only; no customer data or revenue results are shown.</p></section>
      <section className="book-section book-how" aria-labelledby="how-title"><p className="book-kicker">A SIMPLE SYSTEM. A CLEAR NEXT STEP.</p><h2 id="how-title">How it works</h2><div className="book-steps">{steps.map(([title, description], index) => <article key={title}><span className="book-step-number">0{index + 1}</span><h3>{title}</h3><p>{description}</p></article>)}</div></section>
      <section className="book-section book-booking" id="booking" aria-labelledby="booking-title"><div className="book-booking-copy"><p className="book-kicker">LET’S MAKE IT REAL</p><h2 id="booking-title">Want to see it built around your business?</h2><p className="book-section-copy">Book a quick 15-minute demo.</p><div className="book-call-notes"><p><span aria-hidden="true">✓</span> A walkthrough tailored to your business</p><p><span aria-hidden="true">✓</span> A clear view of your lead-to-job process</p><p><span aria-hidden="true">✓</span> Time for your questions</p></div><p className="book-small">A short conversation.<br />A clearer picture of what’s possible.</p></div><BookingForm today={todayInSouthAfrica()} /></section>
    </main><footer className="book-footer"><a className="book-brand" href="/book">Elevate<span className="book-brand-dot">.</span></a><span>More clarity. More opportunity.</span><span>© {new Date().getFullYear()} Elevate</span></footer>
  </div></div>;
}
